# Generated by Django 4.2.1 on 2023-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наличие одежды')),
                ('url', models.SlugField(default='None', max_length=100)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('text', models.TextField(max_length=150, verbose_name='отзыв')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Сезон')),
                ('url', models.SlugField(max_length=150, verbose_name='url-адресс')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Размер')),
                ('url', models.SlugField(default='None', max_length=100)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('contacts', models.TextField(default='отсутствуют', max_length=100, verbose_name='контакты владельца товара')),
                ('sex', models.TextField(max_length=15, verbose_name='Пол')),
                ('cost', models.PositiveSmallIntegerField(help_text='цена в сумах', verbose_name='Цена')),
                ('url', models.SlugField(default='None', max_length=100, unique=True, verbose_name='url-адрес')),
                ('availability', models.ManyToManyField(related_name='availability', to='main.availability', verbose_name='наличие товара')),
                ('seasons', models.ManyToManyField(related_name='season', to='main.season', verbose_name='сезон')),
                ('size', models.ManyToManyField(related_name='size', to='main.size', verbose_name='размер')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
    ]
